version: 0.0 
Resources:
  - LAMBDA_FUNCTION_NAME:
      Type: AWS::Lambda::Function
      Properties:
        Name: "LAMBDA_FUNCTION_NAME"
        Alias: "LAMBDA_FUNCTION_ALIAS"
        CurrentVersion: "CURRENT_VERSION"
        TargetVersion: "TARGET_VERSION"
Hooks:
  - BeforeAllowTraffic: "LAMBDA_FUNCTION_NAME"
  - AfterAllowTraffic: "LAMBDA_FUNCTION_NAME"
